services:
  fastapi-app:
    build: .
    image: merttbayrakttar/annoy-similarity:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host=127.0.0.1 --port=8000
